FROM debian:13-slim

USER root
RUN apt update -y && apt install wget -y && wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linbit.asc -O /etc/apt/keyrings/linbit.asc && wait && wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linstor.sources -O /etc/apt/sources.list.d/linstor.sources && wait && apt update -y
RUN apt install linstor-controller tini linstor-client python3-setuptools -y

# Fetch entrypoint with checksum verification
RUN set -eux; \
    curl -fsSL "$SCRIPT_URL" -o /usr/local/bin/docker-entrypoint-linstor-controller.sh; \
    chmod +x /usr/local/bin/docker-entrypoint-linstor-controller.sh

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/usr/local/bin/docker-entrypoint-linstor-controller.sh"]
